distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https://maven.myket.ir/gradle/distributions/gradle-8.12-all.zip
android.useAndroidX=true
android.util.enableJetifier=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr

