// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi23eQI6FhVQQ4IQHOABsZqT11awVbe70',
    appId: '1:759491111753:web:5183d0516642021ff40898',
    messagingSenderId: '759491111753',
    projectId: 'ai-voice-chat-ac649',
    authDomain: 'ai-voice-chat-ac649.firebaseapp.com',
    storageBucket: 'ai-voice-chat-ac649.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRW_hiHzDEEmTf01lYXphbglJYfjldyfc',
    appId: '1:759491111753:android:7c11f7e319f2fe2af40898',
    messagingSenderId: '759491111753',
    projectId: 'ai-voice-chat-ac649',
    storageBucket: 'ai-voice-chat-ac649.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB6nYNtEtmDoeZ6Dv4_mOTp0xP9HC2iic',
    appId: '1:759491111753:ios:8de8dad89b3434a3f40898',
    messagingSenderId: '759491111753',
    projectId: 'ai-voice-chat-ac649',
    storageBucket: 'ai-voice-chat-ac649.firebasestorage.app',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB6nYNtEtmDoeZ6Dv4_mOTp0xP9HC2iic',
    appId: '1:759491111753:ios:8de8dad89b3434a3f40898',
    messagingSenderId: '759491111753',
    projectId: 'ai-voice-chat-ac649',
    storageBucket: 'ai-voice-chat-ac649.firebasestorage.app',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi23eQI6FhVQQ4IQHOABsZqT11awVbe70',
    appId: '1:759491111753:web:95ae1e77585b4efef40898',
    messagingSenderId: '759491111753',
    projectId: 'ai-voice-chat-ac649',
    authDomain: 'ai-voice-chat-ac649.firebaseapp.com',
    storageBucket: 'ai-voice-chat-ac649.firebasestorage.app',
  );
}
